stages:
  get_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    outs:
    - data_raw.csv  
  process:
    cmd: python pre-processing.py
    deps:
    - pre-processing.py
    - data_raw.csv
    outs:
    - X.csv
    - y.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - X.csv:
        cache: false
    - y.csv:
        cache: false
    outs:
    - confusion_matrix.png
    metrics:
    - metrics.json:
        cache: false
